apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-container
        # image: anokhadocker/user:latest
        image: user:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
